In [ ]:
import numpy as np

In [ ]:
a = np.array(range(10*9)).reshape(10, 9)
b = np.array(range(9)).reshape(9, 1)

np.dot(a, b).shape

(10, 1)

In [ ]:
a = [102, 10, 230, -23, 9, 3, 2, 1]

for i in a:
  print('sig : ', 1 / (1+np.exp(-i)))

sig :  1.0
sig :  0.9999546021312976
sig :  1.0
sig :  1.0261879630648827e-10
sig :  0.9998766054240137
sig :  0.9525741268224334
sig :  0.8807970779778823
sig :  0.7310585786300049


In [ ]:
exp_list = np.linspace(-1, 1, 100)

exp_list

array([-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
       -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182,
       -0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
       -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162,
       -0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
       -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141,
       -0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
       -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121,
       -0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
       -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101,
        0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
        0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919,
        0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
        0.31313131,  0.33333333,  0.35353535,  0.37373737,  0.39

In [ ]:
for i in exp_list:
  print('sig : ', 1 / (1+np.exp(-i)))

In [ ]:
soft_list = [1.2, 0.9, 0.4]

max_v = np.max(soft_list)
soft_list = soft_list - max_v
print(soft_list)
print(np.exp(soft_list) / np.sum(np.exp(soft_list)))

[ 0.  -0.3 -0.8]
[0.45659032 0.33825043 0.20515925]


In [ ]:
import numpy as np

a = [-2, -1, 0, 1, 2]

np.sinh(a) / np.cosh(a)

array([-0.96402758, -0.76159416,  0.        ,  0.76159416,  0.96402758])

In [ ]:
import numpy as np

In [ ]:
def get_fx(x):
  return print(x ** 2 - (2 * x) - 3)

def fx_gd(x):
  return print(2*x - 2)

In [ ]:
d_list = list(range(5))

In [ ]:
for i in d_list:
  get_fx(i)
  fx_gd(i)
  print()

-3
-2

-4
0

-3
2

0
4

5
6



In [ ]:
from tensorflow import keras

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape = (28, 28)))

In [ ]:
model.add(keras.layers.Dense(512, activation = 'relu'))
model.add(keras.layers.Dense(512, activation = 'relu'))

In [ ]:
model.add(keras.layers.Dense(10, activation = 'softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 512)               262656    
                                                                 
 dense_2 (Dense)             (None, 10)                5130      
                                                                 
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [ ]:
784*512*512*10

2055208960

In [ ]:
784*512 + 512

401920

In [ ]:
512*512+512

262656

In [ ]:
512*10+10

5130

In [ ]:
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
model.compile(optimizer = 'adam', loss = keras.losses.SparseCategoricalCrossentropy(from_logits = False), metrics = ['accuracy'])

In [ ]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size = 128, epochs = 20)

Epoch 1/20
469/469 [==============================] - 8s 15ms/step - loss: 2.4148 - accuracy: 0.9034 - val_loss: 0.4361 - val_accuracy: 0.9458
Epoch 2/20
469/469 [==============================] - 7s 15ms/step - loss: 0.3077 - accuracy: 0.9531 - val_loss: 0.3256 - val_accuracy: 0.9528
Epoch 3/20
469/469 [==============================] - 7s 15ms/step - loss: 0.1881 - accuracy: 0.9658 - val_loss: 0.2872 - val_accuracy: 0.9578
Epoch 4/20
469/469 [==============================] - 7s 15ms/step - loss: 0.1416 - accuracy: 0.9728 - val_loss: 0.2759 - val_accuracy: 0.9606
Epoch 5/20
469/469 [==============================] - 7s 16ms/step - loss: 0.1352 - accuracy: 0.9742 - val_loss: 0.2857 - val_accuracy: 0.9578
Epoch 6/20
469/469 [==============================] - 7s 15ms/step - loss: 0.1050 - accuracy: 0.9782 - val_loss: 0.2640 - val_accuracy: 0.9585
Epoch 7/20
469/469 [==============================] - 7s 15ms/step - loss: 0.0800 - accuracy: 0.9813 - val_loss: 0.1917 - val_accuracy: 0.9640